export const activeIcons: Record<string, string> = {
  "BTC-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCBTC.svg",
  "ETH-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCETH.svg",
  "USDT-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCUSDT.svg",
  "XRP-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCXRP.svg",
  "SOL-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCSOL.svg", 
  "DOGE-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCDOGE.svg",
  "ADA-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCADA.svg",
  "LINK-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCLINK.svg",
  "AVAX-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCAVAX.svg",
  "XLM-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCXLM.svg",
  "SUI-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCSUI.svg",
  "BCH-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCBCH.svg",
  "HBAR-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCHBAR.svg",
  "LTC-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCLTC.svg",
  "SHIB-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCSHIB.svg",
  "CRO-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCCRO.svg",
  "DOT-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCDOT.svg",
  "ENA-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCENA.svg",
  "TAO-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCTAO.svg",
  "ETC-USD": "https://s3-symbol-logo.tradingview.com/crypto/XTVCETC.svg",
};
